name: chiken_odyssey
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  equatable: ^2.0.7
  audioplayers: ^6.1.0
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.4.3
  webview_flutter: ^4.4.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/icon_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/png/chiken/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
